"""add description to library

Revision ID: 198586b8910c
Revises: edb83ee6158a
Create Date: 2025-05-23 18:49:05.694855

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '198586b8910c'
down_revision: Union[str, None] = 'edb83ee6158a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('library', sa.Column('description', sa.String(), nullable=True))
    op.execute("UPDATE library SET description = 'No description' WHERE description IS NULL")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('library', 'description')
    # ### end Alembic commands ###
